import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Heading } from "../components/Heading";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DirCmt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mt-2 text-center bg-gray-50">
        <Heading title="DirCmt" />
      </header>
      <main className="container mx-auto bg-gray-50"></main>
      <Footer />
    </div>
  );
};

export default Home;
